### ISSUE TITLE
MEU PERFIL PROFISSIONAL

### ISSUE THREAD

**Issue by marcelogobira** [developers-proseek/lms#4]
. Alterar label OBETIVOS A CURTO PRAZO para OBETIVOS DE CURTO PRAZO 
.. Alterar label OBETIVOS A LONGO PRAZO para OBETIVOS DE LONGO PRAZO

**Comment by JorgeCataldo** [comment]
[ACADEMIA 2.0.xlsx](https://github.com/developers-proseek/lms/files/3779925/ACADEMIA.2.0.xlsx)

**Comment by marcelogobira** [comment]
Tarefa concluída, mas não publicada.

**Comment by marcelogobira** [comment]
> [ACADEMIA 2.0.xlsx](https://github.com/developers-proseek/lms/files/3779925/ACADEMIA.2.0.xlsx)
