### ISSUE TITLE
SITE CHARLIE

### ISSUE THREAD

**Issue by JorgeCataldo** [developers-proseek/lms#90]
- [ ] Reativar site;

**Comment by marcelogobira** [comment]
O IP configurado no GoDaddy está diferente do IP da Instância do Lightsail. Verificar se alguém alterou e o motivo.

**Comment by JorgeCataldo** [comment]
Eu re-startei a instância para ver se voltava... com isso muda o IP... mas
eu estou tentando acessar com o novo IP e nada.
